name: Build And Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
              
    #Setsup node enviroment
    - name: Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    #Create email secrets file:
    - name: create secrets.service.ts
      env:
        EMAIL_TOKEN: ${{ secrets.EMAILTOKEN }}
      run: echo "$EMAIL_TOKEN" | base64 -d > ./src/app/secrets/secret.service.ts

    #run npm install to get node modules, then build
    - name: npm install and npm run build
      run: |
        npm i
        npm run build:prod
        
    #Push build files to /dist folder on github. Uses token in project settings to get acess to push
    - name: Push Build to Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/portfolio/*"
        token: ${{ secrets.TOKEN }}
