name: Build And Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
              
    #Setsup node enviroment
    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    #Create email secrets file:
    - name: create secrets.service.ts {{ secrets.EMAILTOKEN }}
      env:
        EMAIL_TOKEN: ${{ secrets.EMAILTOKEN }}
      run: echo "$EMAIL_TOKEN" | base64 -d > ./src/app/secrets/secret.service.ts
      
    - name: npm install
      run: |
        npm i
    
    - name: npm run build
      run: |
        npm run build:browser:prod
        
    #Push build files to /dist folder on github. Uses token in project settings to get acess to push
    - name: Push Build to /dist
      uses: ncipollo/release-action@v1.7.2
      with:
        artifacts: "dist/portfolio/*"
        token: ${{ secrets.TOKEN }}
